version: "3.8"
services:
  db:
    image: postgres:16
    volumes:
      - psql_db_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: "database_user"
        POSTGRES_PASSWORD: ${SECRET_DB}
        POSTGRES_DB: "main"
    restart: unless-stopped
  backend:
    image: ghcr.io/royalzsoftware/orel/backend:latest
    ports:
      - "8080:8080"
    environment:
        DB_HOST: "db"
        DB_PASSWORD: ${SECRET_DB}
        DB_USER: "database_user"
        DB_DATABASE: "main"
        DB_PORT: "5432"
    restart: unless-stopped
  frontend:
    image: ghcr.io/royalzsoftware/orel/frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
volumes:
  psql_db_data:
