name: "orel"
description: "Build & deploy your project to a remote server with @royalzsoftware/orel"
inputs:
  orel_path:
    required: false
    default: "/home/deployer/orel.config.js"
    description: "The path to the orel.config.js"
  ssh_host:
    required: true
    description: "Hostname for ssh"
  ssh_user:
    default: "deployer"
    required: false
    description: "The ssh username"
  ssh_private_key:
    description: "Key to sign in via ssh"
    required: true
  github_token:
    description: "The github token needed to push to docker"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18.10

    - name: Setup Orel
      shell: bash
      run: |
        npm i -g @royalzsoftware/orel

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Build and push image
      shell: bash
      run: |
        orel push -c ${{ inputs.orel_path }} ${{ inputs.ssh_user }}@${{ inputs.ssh_host }}
    - name: Deploy via SSH
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no ${{ inputs.ssh_user }}@${{ inputs.ssh_host }} << EOF
          sudo orel pull -c /home/${{ inputs.ssh_user }} -u ${{github.actor}} -p ${{inputs.github_token}}
        EOF
